### PR TITLE
make netns test-only dep

### PR DESCRIPTION
**Pull request by stevenctl**
This is preventing `cargo build` on OSX (using the instructions in the README) due to some unresolved imports from `nix` within `netns-rs`.

### CODE REVIEW

**Review by howardjohn — DISMISSED** [review]

**Comment by stevenctl** [comment]
`[cfg(test)]` in `tests/` does nothing...

I think maybe the lib is built separately from the tests so we first built it with the test_helpers excluded :/

**Comment by stevenctl** [comment]
> Cargo will build your library in its normal (non-test) configuration, then build each integration test/benchmark as a sepate binary crate which links to that library. So library code marked with #[cfg(test)] is not available in integration tests/benches.

https://users.rust-lang.org/t/what-are-the-rules-for-cfg-test/54122

Not sure the best way to deal with this. For now just gonna get `cargo build` to work on mac.

**Comment by howardjohn** [comment]
I think we can put integ-only test helpers under test/ possibly (you can make it in a different file if you put it in a folder IIRC. Then we only need test_helpers for things used in unit tests

Or multi crates, main one imports wth cfg=test, integ tests import as normal?

**Comment by stevenctl** [comment]
I believe multi-crates can only have 1 lib crate and N binary crates. 
Workspaces would work around this.. 

 `os = linux` won't work because cargo build attempts to build all the deps upfront. Could make it a cfg=linux specific dependency but the number of guards is getting large, and that's just for one lib. 
 
 I'm going to try CLion's remote development with our build-tools image and a couple of other approaches like devcontainer. 
 
 My goal was just to make sure my IDE functions well enough. I'll need linux to actually run anything anyway.

**Comment by bleggett** [comment]
`My goal was just to make sure my IDE functions well enough. I'll need linux to actually run anything anyway.`

Yeah this is kinda why I'm OK (as a Mac user) with containerized Linux builds - as long as I can build on Linux/$arch I can make do with a container build image, and I prefer those anyway because they're a fixed buildenv.

Also I don't think Istio proper is ever gonna need `ztunnel` to build for macOS - not to say it can't but I think the goal is to support the *nixes and arches Istio ships containers for already as a baseline.


IMO 

- if `ztunnel` can't build for $rust-supported-target-arch, that's a bug/hygiene problem on our end - we shouldn't have arch specific code or assumptions in ztunnel. 
- if `ztunnel` can't build for $rust-supported-target-os then that's a bigger support ask, and case-by-case.

**Comment by stevenctl** [comment]
Agreed. All the code navigation I need works fine even though cargo build doesn't (outside of docker). 
I do think we should still try to prune this dep from the main build though.
